-- ML Tournament backend schema
-- Run this in the Supabase SQL Editor for the project used by the frontend.

create extension if not exists pgcrypto;

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  name text not null,
  color text not null default '#00d4ff',
  seed integer not null,
  logo_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists teams_seed_unique on public.teams(seed);

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  round integer not null check (round between 0 and 5),
  position integer not null check (position >= 0),
  team1_id bigint references public.teams(id) on delete set null,
  team2_id bigint references public.teams(id) on delete set null,
  score1 integer check (score1 is null or score1 >= 0),
  score2 integer check (score2 is null or score2 >= 0),
  winner_id bigint references public.teams(id) on delete set null,
  loser_id bigint references public.teams(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(round, position)
);

create index if not exists matches_round_position_idx on public.matches(round, position);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists teams_updated_at on public.teams;
create trigger teams_updated_at
before update on public.teams
for each row execute function public.set_updated_at();

drop trigger if exists matches_updated_at on public.matches;
create trigger matches_updated_at
before update on public.matches
for each row execute function public.set_updated_at();

-- Production RLS: public can read, only Supabase Auth admins can write.
alter table public.teams enable row level security;
alter table public.matches enable row level security;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'admin' check (role = 'admin'),
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

drop policy if exists "admin_users_self_read" on public.admin_users;
create policy "admin_users_self_read" on public.admin_users
for select to authenticated
using (user_id = auth.uid());

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users
    where user_id = auth.uid() and role = 'admin'
  );
$$;

grant execute on function public.is_admin() to anon, authenticated;

drop policy if exists "teams_public_write" on public.teams;
drop policy if exists "teams_admin_insert" on public.teams;
drop policy if exists "teams_admin_update" on public.teams;
drop policy if exists "teams_admin_delete" on public.teams;

create policy "teams_admin_insert" on public.teams
for insert to authenticated with check (public.is_admin());
create policy "teams_admin_update" on public.teams
for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "teams_admin_delete" on public.teams
for delete to authenticated using (public.is_admin());

drop policy if exists "matches_public_write" on public.matches;
drop policy if exists "matches_admin_insert" on public.matches;
drop policy if exists "matches_admin_update" on public.matches;
drop policy if exists "matches_admin_delete" on public.matches;

create policy "matches_admin_insert" on public.matches
for insert to authenticated with check (public.is_admin());
create policy "matches_admin_update" on public.matches
for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "matches_admin_delete" on public.matches
for delete to authenticated using (public.is_admin());

-- Storage bucket for team logos.
insert into storage.buckets (id, name, public)
values ('team-logos', 'team-logos', true)
on conflict (id) do nothing;

drop policy if exists "team_logos_public_read" on storage.objects;
create policy "team_logos_public_read" on storage.objects
for select using (bucket_id = 'team-logos');

drop policy if exists "team_logos_public_write" on storage.objects;
drop policy if exists "team_logos_admin_insert" on storage.objects;
drop policy if exists "team_logos_admin_update" on storage.objects;
drop policy if exists "team_logos_admin_delete" on storage.objects;

create policy "team_logos_admin_insert" on storage.objects
for insert to authenticated
with check (bucket_id = 'team-logos' and public.is_admin());

create policy "team_logos_admin_update" on storage.objects
for update to authenticated
using (bucket_id = 'team-logos' and public.is_admin())
with check (bucket_id = 'team-logos' and public.is_admin());

create policy "team_logos_admin_delete" on storage.objects
for delete to authenticated
using (bucket_id = 'team-logos' and public.is_admin());
