-- ML Tournament backend schema
-- Run this in the Supabase SQL Editor for the project used by the frontend.

create extension if not exists pgcrypto;

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  name text not null,
  color text not null default '#00d4ff',
  seed integer not null,
  logo_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists teams_seed_unique on public.teams(seed);

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  round integer not null check (round between 0 and 5),
  position integer not null check (position >= 0),
  team1_id bigint references public.teams(id) on delete set null,
  team2_id bigint references public.teams(id) on delete set null,
  score1 integer check (score1 is null or score1 >= 0),
  score2 integer check (score2 is null or score2 >= 0),
  winner_id bigint references public.teams(id) on delete set null,
  loser_id bigint references public.teams(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(round, position)
);

create index if not exists matches_round_position_idx on public.matches(round, position);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists teams_updated_at on public.teams;
create trigger teams_updated_at
before update on public.teams
for each row execute function public.set_updated_at();

drop trigger if exists matches_updated_at on public.matches;
create trigger matches_updated_at
before update on public.matches
for each row execute function public.set_updated_at();

-- The current public viewer/editor uses the Supabase anon key.
-- For production, replace these permissive policies with Supabase Auth
-- policies so only authenticated admins can mutate teams/matches.
alter table public.teams enable row level security;
alter table public.matches enable row level security;

drop policy if exists "teams_public_read" on public.teams;
create policy "teams_public_read" on public.teams
for select using (true);

drop policy if exists "teams_public_write" on public.teams;
create policy "teams_public_write" on public.teams
for all using (true) with check (true);

drop policy if exists "matches_public_read" on public.matches;
create policy "matches_public_read" on public.matches
for select using (true);

drop policy if exists "matches_public_write" on public.matches;
create policy "matches_public_write" on public.matches
for all using (true) with check (true);

-- Storage bucket for team logos.
insert into storage.buckets (id, name, public)
values ('team-logos', 'team-logos', true)
on conflict (id) do nothing;

drop policy if exists "team_logos_public_read" on storage.objects;
create policy "team_logos_public_read" on storage.objects
for select using (bucket_id = 'team-logos');

drop policy if exists "team_logos_public_write" on storage.objects;
create policy "team_logos_public_write" on storage.objects
for all using (bucket_id = 'team-logos') with check (bucket_id = 'team-logos');
